### ISSUE TITLE
unable to get any meaningful response 

### ISSUE THREAD

**Issue by bancroftway** [stumpylog/tika-client#20]
I am pretty sure my apache tika server (version 2.5.0) is running correctly as I have tested it using curl. But the following code is not working as expected:

![image](https://github.com/user-attachments/assets/0760849d-c404-4e04-8d02-7219faab74a4)

**Comment by stumpylog** [comment]
Have you examined the .data attribute?  That's the JSON as returned by the server

**Comment by stumpylog** [comment]
After looking at the relevant code, that is exactly what printing the response should output, so this isn't a bug.

As mentioned in the README, certain attributes will be set or None, depending on the keys Tika decides to return and the `.data` will contain the full JSON data, which can be examined for keys you feel are relevant to your usecases.

In this particular instance, I don't test with PDFs, so I don't know what that format might be.  You will have to decide based on your needs.
