### ISSUE TITLE
ODT File Issues

### ISSUE THREAD

**Issue by shamoon** [stumpylog/tika-client#4]
Tracking
https://github.com/paperless-ngx/paperless-ngx/issues/3780
and
https://github.com/paperless-ngx/paperless-ngx/issues/3757

**Comment by stumpylog** [comment]
If you have time to track a sample file or two, that'd be helpful.  There's at least two odt files already used in the tests, so it's odd to see the Http 500 especially.

I'll be back in a week or so and then I'll look closer

**Comment by locutus13** [comment]
adding a ODT that did not work for testing
[Test.odt](https://github.com/stumpylog/tika-client/files/12016072/Test.odt)

**Comment by sbrunsch2024** [comment]
[20170402-Computertext.odt](https://github.com/stumpylog/tika-client/files/12028708/20170402-Computertext.odt)

**Comment by EKCJ** [comment]
fyi this seems to be a broader issue with tika, I'm also having the same problem using https://github.com/apache/tika-docker but can't see a way to open an issue there.

**Comment by stumpylog** [comment]
Actual Tika issues are here: https://issues.apache.org/jira/projects/TIKA/issues/

**Comment by stumpylog** [comment]
https://github.com/paperless-ngx/paperless-ngx/issues/3757 is something in Tika crashing.  Without a sample, I'm not going to look at it further.  

The fractional seconds ISO parsing (as the dates from LibreOffice are) is implemented in 0.3.0

**Comment by EKCJ** [comment]
If the samples earlier in this thread don't contain what you need, I can try to create one that does. What do you need?

**Comment by stumpylog** [comment]
Nothing else required.  The ISO format dates that LibreOffice writes are handled now
